version: '2.1'
services:
  live-reload:
    container_name: live-reload
    image: node-app
    build: .
    command:
      - npm
      - run
      - live-reload
    volumes:
      - ./:/app
    ports:
      - "3000:3000"

volumes:
  node_modules: {}